{% set name = "inference-tools" %}
{% set version = "0.14.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ce586268ceb0a14f0e488fc984f3607758108337ef333eda20a835ddbb06622f

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools_scm
    - setuptools
  run:
    - python >=3.6
    - numpy >=1.8
    - scipy >=1.6.3
    - importlib-metadata
    - matplotlib >=3.4.2

test:
  imports:
    - inference
  requires:
    - pip
  commands:
    - pip check


about:
  home: "https://github.com/C-bowman/inference-tools/"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "This package provides a set of Python-based tools for Bayesian data analysis which are simple to use, allowing them to applied quickly and easily."
  doc_url: https://inference-tools.readthedocs.io/en/stable/
  dev_url: http://github.com/C-bowman/inference-tools/

extra:
  recipe-maintainers:
    - JarrodLeddy
    - C-bowman
